services:
  postgres:
    image: postgres:15
    container_name: devlife_postgres
    environment:
      POSTGRES_USER: devlife_user
      POSTGRES_PASSWORD: strong_password
      POSTGRES_DB: devlife_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    container_name: devlife_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: devlife_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  mongo_data:
  redis_data: