services:
  
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: devlife_api
    ports:
      - "8080:8080" 
    environment:
     
      - ASPNETCORE_URLS=http://+:8080
      - DATABASE_URL=Host=postgres;Port=5432;Database=devlife_db;Username=devlife_user;Password=strong_password
      - MONGODB_URL=mongodb://mongo:27017
      - REDIS_URL=redis:6379
     
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - JUDGE0_API_KEY=${JUDGE0_API_KEY}
      - JUDGE0_HOST=${JUDGE0_HOST}
      - HOROSCOPE_API_KEY=${HOROSCOPE_API_KEY}
    depends_on:
      - postgres
      - mongo
      - redis


  postgres:
    image: postgres:15
    container_name: devlife_postgres
    environment:
      POSTGRES_USER: devlife_user
      POSTGRES_PASSWORD: strong_password
      POSTGRES_DB: devlife_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  mongo:
    image: mongo:latest
    container_name: devlife_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: devlife_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  mongo_data:
  redis_data: